export const GET_RECORDS_REQUEST = 'GET_RECORDS_REQUEST';
export const GET_RECORDS_SUCCESS = 'GET_RECORDS_SUCCESS';
export const GET_RECORDS_ERROR   = 'GET_RECORDS_ERROR';

export const RECEIVE_ALL_TAGS = 'RECEIVE_ALL_TAGS';
export const EDIT_TAG = 'EDIT_TAG';
export const COMPLETE_EDIT_TAG = 'COMPLETE_EDIT_TAG';