// records
export const GET_RECORDS_REQUEST = 'GET_RECORDS_REQUEST';
export const GET_RECORDS_SUCCESS = 'GET_RECORDS_SUCCESS';
export const GET_RECORDS_ERROR   = 'GET_RECORDS_ERROR';

// subjects
export const LOAD_ALL_SUBJECTS = 'LOAD_ALL_SUBJECTS';
export const LOAD_ALL_SUBJECTS_SUCCESS = 'LOAD_ALL_SUBJECTS_SUCCESS';
export const LOAD_ALL_SUBJECTS_ERROR = 'LOAD_ALL_SUBJECTS_ERROR';

export const CREATE_SUBJECT = 'CREATE_SUBJECT';
export const EDIT_SUBJECT = 'EDIT_SUBJECT';
export const CLOSE_SUBJECT = 'CLOSE_SUBJECT';